version: 2


jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t stevenmburns/tally_image .

      - run: docker run stevenmburns/tally_image bash -c "source /general/bin/activate && pytest -- /general/lib/python3.6/site-packages/tally/tally.py"
